process.env.BUNKER_SKIP_TESTS='1';process.env.BUNKER_SKIP_COLLISION_TESTS='1';
const assert=require('node:assert/strict');
const {world}=require('./test_collisions.cjs');
const {run,source,refs}=require('./test_regressions.cjs');
const r=JSON.parse(source('rooms/Room_Armadilha/Room_Armadilha.yy'));
const walls=r.layers.flatMap(l=>l.instances||[]).filter(i=>i.objectId.name==='Obj_parede');
assert.equal(walls.length,14);
assert(!walls.some(w=>256+11>=w.x&&256-11<w.x+w.scaleX*64&&250+11>=w.y&&250-4<w.y+w.scaleY*64));
const c=world();c.room=refs.Room_Armadilha;c.room_width=512;c.room_height=384;
run(c,'objects/Obj_mapa/Create_0.gml');
assert.equal(c.armadilha_tempo,0);assert.equal(c.global.cutscene_ativa,true);
const full=source('objects/Obj_mapa/Step_0.gml');const start=full.indexOf('if (room == Room_Armadilha &&');const end=full.indexOf('// INTERAÇÕES /',start);const cut=full.slice(start,end);
let destination=null;c.room_goto=x=>destination=x;
for(let i=0;i<48;i++)run(c,'queda',cut);
assert(c.global.armadilha_explodiu);assert(c.audio_is_playing(refs.Snd_explosao));
assert(!c.audio_is_playing(refs.Snd_menu_empresa));
for(let i=48;i<205;i++)run(c,'queda',cut);
assert.equal(destination,refs.Room_Desmoronada);assert.equal(c.global.spawn_x,210);assert.equal(c.global.spawn_y,360);assert(c.global.v5_queda_pendente);assert(!c.global.cutscene_ativa);
console.log('OK: 14 colisores, spawn livre, início da cena, explosão/áudio, chegada à Sala 1 e checkpoint pendente; APIs simuladas.');
